intecomm_ae/urls.py
from django.urls.conf import path
from django.views.generic import RedirectView

app_name = "intecomm_ae"

urlpatterns = [
    path("", RedirectView.as_view(url="/intecomm_ae/admin/"), name="home_url"),
]

intecomm_edc/urls.py
from django.conf import settings
from django.conf.urls.i18n import i18n_patterns
from django.urls.conf import include, path, re_path
from django.views.generic import RedirectView
from edc_auth.views import LogoutView
from edc_dashboard.utils import get_index_page
from edc_dashboard.views import AdministrationView
from edc_utils.paths_for_urlpatterns import paths_for_urlpatterns

from .views import GroupingView, HomeView, SubjectsHomeView

handler403 = "edc_dashboard.views.edc_handler403"
handler404 = "edc_dashboard.views.edc_handler404"
handler500 = "edc_dashboard.views.edc_handler500"

urlpatterns = [
    path("accounts/", include("edc_auth.urls_for_accounts", namespace="auth")),
    path("administration/", AdministrationView.as_view(), name="administration_url"),
    path("subject/", include("intecomm_dashboard.urls")),
    *paths_for_urlpatterns("edc_auth"),
    *paths_for_urlpatterns("edc_action_item"),
    *paths_for_urlpatterns("edc_adverse_event"),
    *paths_for_urlpatterns("edc_appointment"),
    *paths_for_urlpatterns("edc_consent"),
    *paths_for_urlpatterns("edc_crf"),
    *paths_for_urlpatterns("edc_dashboard"),
    *paths_for_urlpatterns("edc_data_manager"),
    *paths_for_urlpatterns("edc_device"),
    *paths_for_urlpatterns("edc_export"),
    *paths_for_urlpatterns("edc_facility"),
    *paths_for_urlpatterns("edc_form_runners"),
    *paths_for_urlpatterns("edc_identifier"),
    *paths_for_urlpatterns("edc_lab"),
    *paths_for_urlpatterns("edc_lab_dashboard"),
    *paths_for_urlpatterns("edc_label"),
    *paths_for_urlpatterns("edc_locator"),
    *paths_for_urlpatterns("edc_metadata"),
    *paths_for_urlpatterns("edc_notification"),
    *paths_for_urlpatterns("edc_offstudy"),
    *paths_for_urlpatterns("edc_pdf_reports"),
    *paths_for_urlpatterns("edc_pdutils"),
    *paths_for_urlpatterns("edc_pharmacy"),
    *paths_for_urlpatterns("edc_protocol"),
    *paths_for_urlpatterns("edc_protocol_incident"),
    *paths_for_urlpatterns("edc_pylabels"),
    *paths_for_urlpatterns("edc_qareports"),
    *paths_for_urlpatterns("edc_qol"),
    *paths_for_urlpatterns("edc_randomization"),
    *paths_for_urlpatterns("edc_refusal"),
    *paths_for_urlpatterns("edc_registration"),
    *paths_for_urlpatterns("edc_review_dashboard"),
    *paths_for_urlpatterns("edc_sites"),
    *paths_for_urlpatterns("edc_subject_dashboard"),
    *paths_for_urlpatterns("edc_unblinding"),
    *paths_for_urlpatterns("edc_visit_schedule"),
    *paths_for_urlpatterns("intecomm_ae"),
    *paths_for_urlpatterns("intecomm_consent"),
    *paths_for_urlpatterns("intecomm_export"),
    *paths_for_urlpatterns("intecomm_facility"),
    *paths_for_urlpatterns("intecomm_lists"),
    *paths_for_urlpatterns("intecomm_prn"),
    *paths_for_urlpatterns("intecomm_group"),
    *paths_for_urlpatterns("intecomm_reports"),
    *paths_for_urlpatterns("intecomm_screening"),
    *paths_for_urlpatterns("intecomm_subject"),
]

if getattr(settings, "DJANGO_DEBUG_TOOLBAR_ENABLED", False):
    urlpatterns.append(
        path("__debug__/", include("debug_toolbar.urls")),
    )

if settings.DEFENDER_ENABLED:
    urlpatterns.append(
        path("defender/", include("defender.urls")),  # defender admin
    )

urlpatterns += [
    path("admin/", RedirectView.as_view(url="/")),
    path(
        "switch_sites/",
        LogoutView.as_view(next_page=get_index_page()),
        name="switch_sites_url",
    ),
    path("grouping/", GroupingView.as_view(), name="screen_group_url"),
    path("subjects/", SubjectsHomeView.as_view(), name="subjects_home_url"),
    path("home/", HomeView.as_view(), name="home_url"),
    path("i18n/", include("django.conf.urls.i18n")),
    re_path(".", RedirectView.as_view(url="/"), name="home_url"),
    re_path("", HomeView.as_view(), name="home_url"),
]

urlpatterns = i18n_patterns(*urlpatterns)

intecomm_reports/urls.py
from django.urls.conf import path
from django.views.generic import RedirectView

app_name = "intecomm_reports"

urlpatterns = [
    path("", RedirectView.as_view(url=f"/{app_name}/admin/"), name="home_url"),
]

intecomm_edc/models.py
# do not delete, need to trigger post-migrate

intecomm_prn/models/proxy.py
from edc_locator.models import SubjectLocator as BaseModel


class SubjectLocator(BaseModel):
    class Meta:
        proxy = True
        verbose_name = "Subject Locator"
        verbose_name_plural = "Subject Locators"

intecomm_edc/views/followup_community_view.py
from typing import Any

from django.conf import settings
from django.views.generic import TemplateView
from edc_dashboard.view_mixins import EdcViewMixin
from edc_navbar import NavbarViewMixin


class FollowupCommunityView(EdcViewMixin, NavbarViewMixin, TemplateView):
    template_name = f"intecomm_edc/bootstrap{settings.EDC_BOOTSTRAP}/followup_community.html"
    navbar_name = settings.APP_NAME
    navbar_selected_item = "community_followup"

    def get_context_data(self, **kwargs) -> dict[str, Any]:
        kwargs.update(
            subject_listboard_url="intecomm_dashboard:community_subject_listboard_url"
        )
        return super().get_context_data(**kwargs)

intecomm_edc/views/followup_inte_view.py
from django.conf import settings
from django.views.generic import TemplateView
from edc_dashboard.view_mixins import EdcViewMixin
from edc_navbar import NavbarViewMixin


class FollowupInteView(EdcViewMixin, NavbarViewMixin, TemplateView):
    template_name = f"intecomm_edc/bootstrap{settings.EDC_BOOTSTRAP}/followup_inte.html"
    navbar_name = settings.APP_NAME
    navbar_selected_item = "inte_followup"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context.update(
            facility_subject_listboard_url="intecomm_dashboard:facility_subject_listboard_url"
        )
        return context

intecomm_edc/views/grouping_view.py
from django.conf import settings
from django.views.generic import TemplateView
from edc_dashboard.view_mixins import EdcViewMixin
from edc_navbar import NavbarViewMixin


class GroupingView(EdcViewMixin, NavbarViewMixin, TemplateView):
    template_name = "intecomm_edc/grouping.html"
    navbar_name = settings.APP_NAME
    navbar_selected_item = "screen_group"

intecomm_edc/views/home_view.py
from django.conf import settings
from django.views.generic import TemplateView
from edc_dashboard.view_mixins import EdcViewMixin
from edc_navbar import NavbarViewMixin


class HomeView(EdcViewMixin, NavbarViewMixin, TemplateView):
    template_name = "intecomm_edc/home.html"
    navbar_name = settings.APP_NAME
    navbar_selected_item = "home"

intecomm_edc/views/subjects_home_view.py
from typing import Any

from django.conf import settings
from django.views.generic import TemplateView
from edc_dashboard.view_mixins import EdcViewMixin
from edc_navbar import NavbarViewMixin


class SubjectsHomeView(EdcViewMixin, NavbarViewMixin, TemplateView):
    template_name = "intecomm_edc/subjects_home.html"
    navbar_name = settings.APP_NAME
    navbar_selected_item = "subjects"

    def get_context_data(self, **kwargs) -> dict[str, Any]:
        kwargs.update(subject_listboard_url="intecomm_dashboard:subject_listboard_url")
        return super().get_context_data(**kwargs)

intecomm_edc/templates/intecomm_edc/base.html
{% extends 'edc_dashboard/base.html' %}
{% block footer %}{{ block.super }} {% comment %}META 2/3 base.html template{% endcomment %}{% endblock footer %}

intecomm_edc/templates/intecomm_edc/followup_community.html
{% extends 'intecomm_edc/base.html' %}
{% load static edc_dashboard_extras %}

{% block main %}

<style>

.bg-1 {
    background-color: #428bca; /* dark blue */
    color: #ffffff;
}
.bg-2 {
    background-color: #5bc0de; /* light Blue */
    color: #ffffff;
}
.bg-3 {
    background-color: #f9f9f9; /* White */
    color: #555555;
}

</style>

{{ block.super }}



<div class="row">

  <div class="col-sm-4">&nbsp;</div>
  <div class="col-sm-4">
    <div class="panel panel-default">
      <div class="panel-heading"><i class="fas fa-users-between-lines fa-lg fa-fw" aria-hidden="true"></i> Community-care at {{ site_title|default:request.site.name|title }}</div>
      <div class="list-group">
        <a id="home_list_group_home" href="{% url 'home_url' %}" class="list-group-item"><i class="fas fa-reply fa-1x fa-fw" aria-hidden="true"></i> Home</a>
      {% if perms.edc_subject_dashboard.view_subject_listboard %}
        <a id="home_list_group_subject_listboard" href="{% url subject_listboard_url|default:'subject_listboard_url_cannot_be_none' %}" class="list-group-item"><i class="fas fa-user-circle fa-lg fa-fw"></i>&nbsp;&nbsp;&nbsp;
          Subjects</a>
      {% endif %}
      {% if perms.edc_review_dashboard.view_subject_review_listboard %}
        <a id="home_list_group_subject_review_listboard" href="{% url subject_review_listboard_url|default:'subject_review_listboard_url_cannot_be_none' %}" class="list-group-item"><i class="fas fa-calendar fa-lg fa-fw"></i>&nbsp;&nbsp;&nbsp;Subject Review</a>
      {% endif %}
      {% if perms.edc_locator.view_subjectlocator %}
        <a id="home_list_group_subject_locator" href="{% url 'intecomm_prn_admin:intecomm_prn_subjectlocator_changelist' %}" class="list-group-item"><i class="fas fa-location-dot fa-lg fa-fw"></i>&nbsp;&nbsp;&nbsp;Subject Locator</a>
      {% endif %}
      {% if perms.edc_adverse_event.nav_ae_section %}
        <a id="home_list_group_ae" href="{% url 'edc_adverse_event:ae_home_url' %}" class="list-group-item"><i class="fas fa-heartbeat fa-lg fa-fw"></i>&nbsp;&nbsp;&nbsp;Adverse events</a>
      {% endif %}
      {% if perms.edc_adverse_event.nav_tmg_section %}
        <a id="home_list_group_aetmg" href="{% url 'edc_adverse_event:tmg_home_url' %}" class="list-group-item"><i class="fas fa-heartbeat fa-lg fa-fw"></i>&nbsp;&nbsp;&nbsp;TMG Reports</a>
      {% endif %}
      </div>
    </div>
  </div>
  <div class="col-sm-4">&nbsp;
  </div>
</div>



{% endblock main %}

intecomm_edc/templates/intecomm_edc/grouping.html
{% extends 'intecomm_edc/base.html' %}
{% load static edc_dashboard_extras %}
{% load edc_sites_extras %}

{% block main %}

<style>

.bg-1 {
    background-color: #428bca; /* dark blue */
    color: #ffffff;
}
.bg-2 {
    background-color: #5bc0de; /* light Blue */
    color: #ffffff;
}
.bg-3 {
    background-color: #f9f9f9; /* White */
    color: #555555;
}

</style>

{{ block.super }}

<div class="row">

  <div class="col-sm-4">&nbsp;</div>
  <div class="col-sm-4">
    <div class="panel panel-default">
      <div class="panel-heading">Screening and Grouping</div>
      <div class="list-group">
        <a id="home_list_group_home" href="{% url 'home_url' %}" class="list-group-item"><i class="fas fa-reply fa-1x fa-fw" aria-hidden="true"></i> Home</a>
      {% if perms.intecomm_screening.view_healthtalklog %}
        <a id="home_list_group_healthtalklog" href="{% url 'intecomm_screening_admin:intecomm_screening_healthtalklog_changelist' %}" class="list-group-item"><i class="fas fa-users-between-lines fa-lg fa-fw"></i>&nbsp;&nbsp;&nbsp;Health Talk Log</a>
      {% endif %}
      {% if perms.intecomm_screening.view_patientlog %}
        {% if request|country == "uganda" %}
          <a id="home_list_group_patientlog" href="{% url 'intecomm_screening_admin:intecomm_screening_patientlogug_changelist' %}" class="list-group-item"><i class="fas fa-person-circle-plus fa-lg fa-fw"></i>&nbsp;&nbsp;&nbsp;Patient Log</a>
        {% else %}
          <a id="home_list_group_patientlog" href="{% url 'intecomm_screening_admin:intecomm_screening_patientlog_changelist' %}" class="list-group-item"><i class="fas fa-person-circle-plus fa-lg fa-fw"></i>&nbsp;&nbsp;&nbsp;Patient Log</a>
        {% endif %}
      {% endif %}
      {% if perms.intecomm_screening.view_patientgroup %}
        <a id="home_list_group_patientgroup" href="{% url 'intecomm_screening_admin:intecomm_screening_patientgroup_changelist' %}" class="list-group-item"><i class="fas fa-users fa-lg fa-fw"></i>&nbsp;&nbsp;&nbsp;Manage Patient Groups</a>
      {% endif %}
      </div>
    </div>
  </div>
  <div class="col-sm-4">&nbsp;
  </div>
</div>

{% endblock main %}

intecomm_edc/templates/intecomm_edc/home.html
{% extends 'intecomm_edc/base.html' %}
{% load static edc_dashboard_extras %}

{% block main %}

<style>
a { cursor: pointer; }
.bg-1 {
    background-color: #428bca; /* dark blue */
    color: #ffffff;
}
.bg-2 {
    background-color: #5bc0de; /* light Blue */
    color: #ffffff;
}
.bg-3 {
    background-color: #f9f9f9; /* White */
    color: #555555;
}

</style>

{{ block.super }}
<form id="switch_sites_form" method="post" action="{% url 'switch_sites_url' %}">{% csrf_token %}</form>
<form id="logout_form" method="post" action="{% url 'edc_auth_admin:logout' %}">{% csrf_token %}</form>

<div class="row">

  <div class="col-sm-4">&nbsp;</div>
  <div class="col-sm-4">
    <div class="panel panel-default">
      <div class="panel-heading">{{ protocol_name |default:project_name }} {{ site_title|default:request.site.name|title }}</div>
      <div class="list-group">
        <a href="#" class="list-group-item disabled">Screening and Grouping</a>
        <a id="logs_list_group_home" href="{% url 'screen_group_url' %}" class="list-group-item"><i class="fas fa-users fa-lg fa-fw" aria-hidden="true"></i> Patient Logs / Patient Groups</a>
        <a href="#" class="list-group-item disabled">Follow-up</a>
        <a id="followup_list_group_home" href="{% url 'subjects_home_url' %}" class="list-group-item"><i class="fas fa-user-circle fa-lg fa-fw" aria-hidden="true"></i> Subjects</a>
        <a href="#" class="list-group-item disabled">General</a>
        {% if perms.edc_action_item.nav_action_item_section %}
          <a href="{% url 'edc_action_item:home_url' %}" class="list-group-item"><i class="fas fa-bolt fa-lg fa-fw"></i>&nbsp;&nbsp;&nbsp;Action items</a>
        {% endif %}
        {% if perms.edc_data_manager.nav_data_manager_section %}
          <a href="{% url 'edc_data_manager:home_url' %}" class="list-group-item"><i class="fas fa-database fa-lg fa-fw"></i>&nbsp;&nbsp;&nbsp;Data Management</a>
        {% endif %}
        {% if perms.edc_export %}
          <a href="{% url 'edc_export:home_url' %}" class="list-group-item"><i class="fas fa-file-export fa-lg fa-fw"></i>&nbsp;&nbsp;&nbsp;Export data</a>
        {% endif %}
        {% if perms.intecomm_reports %}
          <a href="{% url 'intecomm_reports:home_url' %}" class="list-group-item"><i class="fa-solid fa-stroopwafel fa-lg fa-fw"></i></i>&nbsp;&nbsp;&nbsp;QA Reports</a>
        {% endif %}
        {% if perms.edc_auth.change_userprofile %}
          <a href="{% url 'edc_auth:home_url' %}" class="list-group-item"><i class="fas fa-users fa-lg fa-fw"></i>&nbsp;&nbsp;&nbsp;Account Management</a>
        {% endif %}
          <a onclick="document.getElementById('switch_sites_form').submit();" class="list-group-item" title="{% url 'switch_sites_url' %}"><i class="fas fa-arrows-alt fa-lg fa-fw"></i>&nbsp;&nbsp;&nbsp;Switch sites</a>
          <a onclick="document.getElementById('logout_form').submit();" class="list-group-item" title="{% url 'edc_auth_admin:logout' %}"><i class="fas fa-sign-out-alt fa-lg fa-fw"></i>&nbsp;&nbsp;&nbsp;Log out</a>
      </div>
    </div>
  </div>
  <div class="col-sm-4">&nbsp;
  </div>
</div>



{% endblock main %}

intecomm_edc/templates/intecomm_edc/subjects_home.html
{% extends 'intecomm_edc/base.html' %}
{% load static edc_dashboard_extras %}

{% block main %}

<style>

.bg-1 {
    background-color: #428bca; /* dark blue */
    color: #ffffff;
}
.bg-2 {
    background-color: #5bc0de; /* light Blue */
    color: #ffffff;
}
.bg-3 {
    background-color: #f9f9f9; /* White */
    color: #555555;
}

</style>

{{ block.super }}



<div class="row">

  <div class="col-sm-4">&nbsp;</div>
  <div class="col-sm-4">
    <div class="panel panel-default">
      <div class="panel-heading"><i class="fas fa-user-circle fa-lg fa-fw" aria-hidden="true"></i> Subjects at {{ site_title|default:request.site.name|title }}</div>
      <div class="list-group">
        <a id="home_list_group_home" href="{% url 'home_url' %}" class="list-group-item"><i class="fas fa-reply fa-1x fa-fw" aria-hidden="true"></i> Home</a>
      {% if perms.edc_subject_dashboard.view_subject_listboard %}
        <a id="home_list_group_subject_listboard" href="{% url subject_listboard_url|default:'subject_listboard_url_cannot_be_none' %}" class="list-group-item"><i class="fas fa-user-circle fa-lg fa-fw"></i>&nbsp;&nbsp;&nbsp;
          Subjects</a>
      {% endif %}
      {% if perms.edc_review_dashboard.view_subject_review_listboard %}
        <a id="home_list_group_subject_review_listboard" href="{% url subject_review_listboard_url|default:'subject_review_listboard_url_cannot_be_none' %}" class="list-group-item"><i class="fas fa-calendar fa-lg fa-fw"></i>&nbsp;&nbsp;&nbsp;Subject Review</a>
      {% endif %}
      {% if perms.edc_locator.view_subjectlocator %}
        <a id="home_list_group_subject_locator" href="{% url 'intecomm_prn_admin:intecomm_prn_subjectlocator_changelist' %}" class="list-group-item"><i class="fas fa-location-dot fa-lg fa-fw"></i>&nbsp;&nbsp;&nbsp;Subject Locator</a>
      {% endif %}
      {% if perms.edc_adverse_event.nav_ae_section %}
        <a id="home_list_group_ae" href="{% url 'edc_adverse_event:ae_home_url' %}" class="list-group-item"><i class="fas fa-heartbeat fa-lg fa-fw"></i>&nbsp;&nbsp;&nbsp;Adverse events</a>
      {% endif %}
      {% if perms.edc_adverse_event.nav_tmg_section %}
        <a id="home_list_group_aetmg" href="{% url 'edc_adverse_event:tmg_home_url' %}" class="list-group-item"><i class="fas fa-heartbeat fa-lg fa-fw"></i>&nbsp;&nbsp;&nbsp;TMG Reports</a>
      {% endif %}
      </div>
    </div>
  </div>
  <div class="col-sm-4">&nbsp;
  </div>
</div>



{% endblock main %}